# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::090212595461:role/UdacityFlaskDeployCBKubectlRole
      username: build
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::090212595461:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IE52HOWTSAZC
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-31T10:26:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1794"
  uid: 72c2c087-3562-4625-9fe0-9266ddc20bf1
